import type { ResourceConfig } from "../services/crud/crud.service.js";
import {
  BlogPost,
  Category,
  Destination,
  Excursion,
  FAQ,
  GalleryItem,
  GuestShort,
  HeroMedia,
  NavigationItem,
  Review,
  SeoMetadata,
  Tour,
  Vehicle,
} from "../models/index.js";
import * as v from "../validations/content.js";
import { CACHE_TAGS } from "../services/revalidate.service.js";

const categoryPopulate = { path: "category", select: "name slug kind" };

/** Declarative configuration for every CMS content type handled by the generic CRUD layer. */
export const RESOURCES = {
  tours: {
    name: "tour",
    label: "Tour",
    model: Tour,
    permission: "tours",
    createSchema: v.tourCreate,
    updateSchema: v.tourUpdate,
    searchFields: ["title", "slug", "shortDescription"],
    slugFrom: "title",
    defaultSort: { order: 1, createdAt: -1 },
    filters: { status: "status", category: "category", featured: "featured", destination: "destinations" },
    populate: [categoryPopulate],
    listSelect: "title slug status featured order durationDays durationNights price currency heroMedia category updatedAt",
    cacheTags: [CACHE_TAGS.tours],
    translatable: "tour",
    publishField: "status",
  },
  destinations: {
    name: "destination",
    label: "Destination",
    model: Destination,
    permission: "destinations",
    createSchema: v.destinationCreate,
    updateSchema: v.destinationUpdate,
    searchFields: ["name", "slug", "region"],
    slugFrom: "name",
    defaultSort: { order: 1, name: 1 },
    filters: { status: "status", category: "category", featured: "featured" },
    populate: [categoryPopulate],
    listSelect: "name slug region status featured order heroMedia category updatedAt",
    cacheTags: [CACHE_TAGS.destinations],
    translatable: "destination",
    publishField: "status",
  },
  excursions: {
    name: "excursion",
    label: "Excursion",
    model: Excursion,
    permission: "excursions",
    createSchema: v.excursionCreate,
    updateSchema: v.excursionUpdate,
    searchFields: ["title", "slug", "location"],
    slugFrom: "title",
    defaultSort: { order: 1, createdAt: -1 },
    filters: { status: "status", category: "category", featured: "featured", destination: "destination" },
    populate: [categoryPopulate],
    listSelect: "title slug status featured order duration price currency heroMedia category location updatedAt",
    cacheTags: [CACHE_TAGS.excursions],
    translatable: "excursion",
    publishField: "status",
  },
  vehicles: {
    name: "vehicle",
    label: "Vehicle",
    model: Vehicle,
    permission: "vehicles",
    createSchema: v.vehicleCreate,
    updateSchema: v.vehicleUpdate,
    searchFields: ["name", "type"],
    slugFrom: "name",
    defaultSort: { order: 1, createdAt: -1 },
    filters: { status: "status", category: "category", featured: "featured" },
    populate: [categoryPopulate],
    listSelect: "name slug type seats luggageCapacity status featured order images dailyRate currency availability category updatedAt",
    cacheTags: [CACHE_TAGS.vehicles],
    translatable: "vehicle",
    publishField: "status",
  },
  categories: {
    name: "category",
    label: "Category",
    model: Category,
    permission: "categories",
    createSchema: v.categoryCreate,
    updateSchema: v.categoryUpdate,
    searchFields: ["name", "slug"],
    slugFrom: "name",
    slugScope: ["kind"],
    defaultSort: { kind: 1, order: 1, name: 1 },
    filters: { kind: "kind" },
    cacheTags: [CACHE_TAGS.categories, CACHE_TAGS.tours, CACHE_TAGS.excursions, CACHE_TAGS.blog, CACHE_TAGS.gallery],
    translatable: "category",
    publishField: "enabled",
  },
  gallery: {
    name: "galleryItem",
    label: "Gallery",
    model: GalleryItem,
    permission: "gallery",
    createSchema: v.galleryCreate,
    updateSchema: v.galleryUpdate,
    searchFields: ["title", "caption", "tags"],
    defaultSort: { order: 1, createdAt: -1 },
    filters: { status: "status", category: "category", featured: "featured", resourceType: "media.resourceType" },
    populate: [categoryPopulate],
    cacheTags: [CACHE_TAGS.gallery],
    translatable: "galleryItem",
    publishField: "status",
    duplicateTitleField: "title",
  },
  blog: {
    name: "blogPost",
    label: "Blog post",
    model: BlogPost,
    permission: "blog",
    createSchema: v.blogCreate,
    updateSchema: v.blogUpdate,
    searchFields: ["title", "slug", "excerpt", "tags"],
    slugFrom: "title",
    defaultSort: { publishDate: -1 },
    filters: { status: "status", category: "category", featured: "featured" },
    populate: [categoryPopulate],
    listSelect: "title slug status featured publishDate coverImage category author updatedAt",
    cacheTags: [CACHE_TAGS.blog],
    translatable: "blogPost",
    publishField: "status",
  },
  guestShorts: {
    name: "guestShort",
    label: "Guest short",
    model: GuestShort,
    permission: "guestShorts",
    createSchema: v.guestShortCreate,
    updateSchema: v.guestShortUpdate,
    searchFields: ["title", "guestName", "country"],
    defaultSort: { order: 1, date: -1 },
    filters: { status: "status", featured: "featured", platform: "platform" },
    cacheTags: [CACHE_TAGS.guestShorts],
    translatable: "guestShort",
    publishField: "status",
    duplicateTitleField: "title",
  },
  reviews: {
    name: "review",
    label: "Review",
    model: Review,
    permission: "reviews",
    createSchema: v.reviewCreate,
    updateSchema: v.reviewUpdate,
    searchFields: ["guestName", "country", "review", "title"],
    defaultSort: { date: -1 },
    filters: { status: "status", featured: "featured", platform: "platform" },
    cacheTags: [CACHE_TAGS.reviews],
    publishField: "status",
    duplicateTitleField: "guestName",
  },
  faqs: {
    name: "faq",
    label: "FAQ",
    model: FAQ,
    permission: "faqs",
    createSchema: v.faqCreate,
    updateSchema: v.faqUpdate,
    searchFields: ["question", "answer", "category"],
    defaultSort: { order: 1, createdAt: 1 },
    filters: { status: "status", featured: "featured" },
    cacheTags: [CACHE_TAGS.faqs],
    translatable: "faq",
    publishField: "status",
    duplicateTitleField: "question",
  },
  hero: {
    name: "heroMedia",
    label: "Hero slide",
    model: HeroMedia,
    permission: "hero",
    createSchema: v.heroCreate,
    updateSchema: v.heroUpdate,
    searchFields: ["title", "subtitle"],
    defaultSort: { order: 1 },
    cacheTags: [CACHE_TAGS.hero],
    translatable: "heroMedia",
    publishField: "enabled",
    duplicateTitleField: "title",
  },
  navigation: {
    name: "navigationItem",
    label: "Menu item",
    model: NavigationItem,
    permission: "navigation",
    createSchema: v.navigationCreate,
    updateSchema: v.navigationUpdate,
    searchFields: ["label", "url"],
    defaultSort: { order: 1 },
    cacheTags: [CACHE_TAGS.navigation],
    translatable: "navigationItem",
    publishField: "enabled",
    duplicateTitleField: "label",
  },
  seo: {
    name: "seoMetadata",
    label: "SEO",
    model: SeoMetadata,
    permission: "seo",
    createSchema: v.seoMetadataCreate,
    updateSchema: v.seoMetadataUpdate,
    searchFields: ["key", "seoTitle"],
    defaultSort: { key: 1 },
    cacheTags: [CACHE_TAGS.seo],
  },
} satisfies Record<string, ResourceConfig>;
